### PR TITLE
Updated Ansh Singh Sonkhia Code

### PR DESCRIPTION
**Pull request by AnshSinghSonkhia**
Added the code for Ansh.

Kindly, Merge this PR with the `hacktoberfest-accepted` label.

### CODE REVIEW

**Comment by Rajkumar-justcoder** [comment]
Hey there, Just can u resolve conflict caused by icon change + also update with yours one

**Comment by AnshSinghSonkhia** [comment]
Hey @Rajkumar-justcoder Ji, I can't understand what's the conflict. Can you please resolve the conflict or help me out?

When I raised the PR, it was not showing any conflict at that time.
Kindly Help Me Out!

**Comment by Rajkumar-justcoder** [comment]
> Hey @Rajkumar-justcoder Ji, I can't understand what's the conflict. Can you please resolve the conflict or help me out?
> 
> When I raised the PR, it was not showing any conflict at that time. Kindly Help Me Out!

hey to solve conflict pls close this pull request and fetch new code and then add your name to it cause 
one pr was merged which have some update to it related to emoji and icons
so at a time of pr u should fetch and pull again / means sync your forked repo and then 

sry i cant change whole file for conflict else i would have done

**Comment by AnshSinghSonkhia** [comment]
Okay, I understood, give me an hour or two.

**Pull request closed without merging**
