### PR TITLE
Added Name

### PR DESCRIPTION
**Pull request by Milind-Palaria**

### CODE REVIEW

**Comment by Milind-Palaria** [comment]
@Rajkumar-justcoder as u said i re-pushed the code. Now, you can merge this.

**Comment by Rajkumar-justcoder** [comment]
Why css code is modified this much and adding ; at last properly of css 
In css we can remove semi colon form last property

Pls add ss of modifications cause u are using some cdn and some icon packs with json files

**Comment by Milind-Palaria** [comment]
Thanks for the suggestions @Rajkumar-justcoder. CSS code is modified so much just to revamp the site and give it a little better look. Margins had to be use it to align text and icon from top-left corner to better looking centre area. Icon packs are used for same reason. it would be really helpful if you could merge this code. Raising a pull request again would become hectic. Will really appreciate if u could merge this code only, although i really appreciate your suggestions, Thank You.

**Comment by Rajkumar-justcoder** [comment]
Okay nvm
merging its 
i was telling because there was some thing to so with that test on left side so

**Pull request merged**
